document.addEventListener('DOMContentLoaded',async()=>{
 const $=id=>document.getElementById(id), input=$('textInput');
 function send(){if(input.value.trim())window.siaChat.submitMessage(input.value);}
 $('btnSendText').onclick=send;input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();send();}};
 $('btnVoiceInput').onclick=()=>window.siaVoice.toggleListening();$('btnStopSpeech').onclick=()=>window.siaVoice.interrupt();
 addEventListener('keydown',e=>{if(e.code==='Space'&&document.activeElement!==input&&!e.repeat){e.preventDefault();window.siaVoice.startListening();}if(e.key==='Escape'){window.siaVoice.interrupt();$('settingsModal').style.display='none';$('confirmationModal').style.display='none';$('memoryDrawer').classList.remove('open');}});
 addEventListener('keyup',e=>{if(e.code==='Space'&&document.activeElement!==input){e.preventDefault();window.siaVoice.stopListening();}});
 window.siaApi.on('state',(state)=>{window.siaAvatar?.setState(state);$('statusLabel').textContent=String(state).toUpperCase();$('systemStatusBadge').className='status '+state;});
 window.siaApi.on('response',p=>window.siaChat.handleSiaResponse(p));
 async function load(){const [st,set,key]=await Promise.all([window.siaApi.status(),window.siaApi.settings(),window.siaApi.keyStatus()]);$('assistantName').textContent=st.assistant_name;$('settingAssistantName').value=set.assistant.name;$('settingUserName').value=set.user.name;$('settingProvider').value=set.ai.provider;$('settingGeminiModel').value=set.ai.gemini_model;$('settingVoice').value=set.ai.gemini_voice;$('geminiStatusText').textContent=key.configured?' Gemini key configured.':' No Gemini key configured; local mode remains available.';}
 load();
 $('btnMemory').onclick=async()=>{const d=$('memoryDrawer');d.classList.add('open');const [m,t]=await Promise.all([window.siaApi.memories(),window.siaApi.tasks()]);$('drawerMemoriesList').innerHTML=m.length?m.map(x=>`<div class="memory-card"><b>${window.siaChat.escape(x.key)}</b><span>${window.siaChat.escape(x.value)}</span></div>`).join(''):'<div class="empty">No memories yet.</div>';$('drawerTasksList').innerHTML=t.length?t.map(x=>`<div class="task-card"><b>${window.siaChat.escape(x.title)}</b><button class="text-btn" onclick="window.siaApi.completeTask(${x.id})">Done</button></div>`).join(''):'<div class="empty">No tasks.</div>';};
 $('btnCloseMemory').onclick=()=>$('memoryDrawer').classList.remove('open');
 $('btnSettings').onclick=()=>$('settingsModal').style.display='flex';$('btnCloseSettings').onclick=()=>$('settingsModal').style.display='none';
 $('btnSaveSettings').onclick=async()=>{const s=await window.siaApi.settings();s.assistant.name=$('settingAssistantName').value.trim()||'SIA';s.user.name=$('settingUserName').value.trim()||'Sagar';s.ai.provider=$('settingProvider').value;s.ai.gemini_model=$('settingGeminiModel').value.trim()||'gemini-3.8-flash';s.ai.gemini_voice=$('settingVoice').value;s.voice.engine=s.ai.provider==='local'?'edge-tts':'gemini';await window.siaApi.saveSettings(s);const key=$('settingGeminiKey').value.trim();if(key)await window.siaApi.setKey(key);$('assistantName').textContent=s.assistant.name;$('settingsModal').style.display='none';$('coreStatusText').textContent='Settings saved';window.siaAvatar?.setState('success');setTimeout(()=>window.siaAvatar?.setState('idle'),800);};
 $('btnTestVoice').onclick=async()=>{const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:`Hello ${$('settingUserName').value||'Sir'}. This is my current assistant voice.`,language:'en'})});const d=await r.json();if(d.audio_base64)window.siaVoice.playAudioResponse(d.audio_base64,d.mime_type||'audio/wav');};
 $('btnApproveConfirm').onclick=async()=>{const m=$('confirmationModal'),id=m.dataset.currentId;m.style.display='none';const r=await window.siaApi.confirmAction(id,true);if(r.tool_result)window.siaChat.appendAssistantMessage(r.tool_result.message||'Action executed.',r.tool_result);window.siaAvatar?.setState('idle');};
 $('btnRejectConfirm').onclick=async()=>{const m=$('confirmationModal'),id=m.dataset.currentId;m.style.display='none';await window.siaApi.confirmAction(id,false);window.siaChat.appendAssistantMessage('Understood, Sir. I cancelled that action.');window.siaAvatar?.setState('idle');};
});
