class SiaChatManager {
  constructor(){this.panel=document.getElementById('transcriptPanel');}
  escape(s){const d=document.createElement('div');d.textContent=s??'';return d.innerHTML;}
  appendUserMessage(text){const el=document.createElement('div');el.className='transcript-line user';el.innerHTML=`<span class="speaker">YOU</span><span>${this.escape(text)}</span>`;this.panel.appendChild(el);this.panel.scrollTop=this.panel.scrollHeight;}
  appendAssistantMessage(text,tool){const el=document.createElement('div');el.className='transcript-line assistant';let extra='';if(tool?.success&&tool?.data){extra=`<div class="tool-chip">✓ ${this.escape(tool.message||'Action completed')}</div>`;}el.innerHTML=`<span class="speaker">SIA</span><span>${this.escape(text)}</span>${extra}`;this.panel.appendChild(el);this.panel.scrollTop=this.panel.scrollHeight;}
  async submitMessage(text){const clean=(text||'').trim();if(!clean)return;this.appendUserMessage(clean);document.getElementById('textInput').value='';window.siaAvatar?.setState('thinking');document.getElementById('coreStatusText').textContent='Thinking…';try{const res=await window.siaApi.sendChatMessage(clean,true);if(res)this.handleSiaResponse(res);}catch(e){this.appendAssistantMessage('Sir, I cannot reach the local assistant core right now.');window.siaAvatar?.setState('idle');}}
  handleSiaResponse(data){if(data.requires_confirmation){this.showConfirmation(data);window.siaAvatar?.setState('thinking');return;}this.appendAssistantMessage(data.response_text,data.tool_result);window.siaAvatar?.setState(data.state||'idle');document.getElementById('coreStatusText').textContent=data.state==='speaking'?'Speaking…':'Standing by';if(data.audio_base64)window.siaVoice.playAudioResponse(data.audio_base64,data.mime_type||'audio/wav');}
  showConfirmation(data){const m=document.getElementById('confirmationModal');m.dataset.currentId=data.confirmation_id;document.getElementById('confirmDescription').textContent=data.response_text;document.getElementById('confirmDetails').textContent=JSON.stringify(data.tool_result?.parameters||{},null,2);document.getElementById('confirmRiskBadge').textContent=(data.tool_result?.risk_level||'MEDIUM')+' RISK';m.style.display='flex';}
}
window.siaChat=new SiaChatManager();
